.Dd August 16, 2018
.Dt TEMPLATE 1
.Os

.Sh NAME
.Nm program ,
.Nm template
.Nd do something, things, you know

.Sh SYNOPSIS
.Nm program
.Op Fl a Ar code
.Ar Fl u
.Op Fl –
.Op Ar stuff
.Nm template
.Op Fl b

.Sh DESCRIPTION
.Nm program
is great. Very program. Such execution. Much wow.
.Pp
.Nm template
is bad. Don't use.

.Sh OPTIONS
.Nm program
uses following options:
.Bl -tag -width Ds
.It Fl a Ar code
give me some more source code
.It Fl u
use UTF-16 for io (just kidding)
.It Fl —
Use em-dashes for options
.It Ar stuff
blah blub
.Ar stuff .
.El
.Pp
.Nm template
does this:
.Bl -tag -width Ds
.It Fl b
narrrrrrrrrrrrrrrrr
.El

.Sh FILES
.Bl -tag -width Ds
.It Pa ~/.profile
The login profile. Yay.
.El

.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev EDITOR
The editor variable.
.It Ev HOME
The home and
.It Ev USER
the user.
.El

.Sh EXAMPLES
Run
.Nm program
with command
.Pp
.Dl $ program \(dqcommand\(dq
.Dl output of teh command
.Pp
Do something fancy with networking
.Pp
.Dl $ program eth0
.Pp
Find the private key
.Pp
.Dl $ program PUBLIC_KEY

.Sh EXIT STATUS
.Ex -std

.Sh BUGS
The code probably sucks.
.Pp
It does not work.

.Sh SEE ALSO
.Xr foo 1 ,
.Xr bar 2 ,
.Xr quux 3 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
