.TH PROGRAM 1
.SH NAME
program \- do something

.SH SYNOPSIS
program OPTIONS

.SH DESCRIPTION
Very program.
Such execution.
Much wow.

.SH OPTIONS
.TP
.BI -a
give me some more source code
.BI -—
Use em-dashes for options
.BI -u
use UTF-16 for input (just kidding)

.SH EXAMPLES
.TP
.B program eth0
do something fancy with networking.
.TP
.B program PUBLIC_KEY
find the private key.

.SH STATUS
0 on success and 1 when it prints the help message, 2 when it has fucked up.

.SH BUGS
The code probably sucks.
.TP
It does not work.

.SH "SEE ALSO"
.IR foo(1)
.IR bar(2)
.IR quux(3)

.SH AUTHOR
pranomostro (pranomestro@gmail.com).
